### ISSUE TITLE
Add 'gradio' to requirements.txt

### ISSUE THREAD

**Issue by arky** [macaodha/batdetect2#13]
Perhaps it is a good idea to add `gradio` to environment as it is being used by the app.py

**Comment by mbsantiago** [comment]
Thank you for your suggestion, @arky! The reason we didn't include gradio in the environment is that it's not essential for the model to run. The app.py module primarily focuses on setting up the visualization app hosted at Hugging Face, and in their environment, gradio is already installed. But if you still believe it would be nice to include gradio please let us know your thoughts. Thanks again!

**Comment by arky** [comment]
Indeed @mbsantiago, Makes perfect sense.

Guess I am part of select few who like to try out Gradio interface on my machine and conda environment.
