### ISSUE TITLE
Strange results when applying the --spec_features flag

### ISSUE THREAD

**Issue by jenstangchristensen** [macaodha/batdetect2#15]
Using the flag “--spec_features” I get a .csv file containing only the value -1.00000 for all cells.
[M00052.WAV.csv](https://github.com/macaodha/batdetect2/files/12112528/M00052.WAV.csv)
[M00052.WAV_spec_features.csv](https://github.com/macaodha/batdetect2/files/12112529/M00052.WAV_spec_features.csv)

**Comment by macaodha** [comment]
Thanks for flagging this. We will take a look and report back soon.

**Comment by macaodha** [comment]
Hi both. Santiago, took a look at this and fixed some issues in the code. The newly updated version should hopefully work as expected. Let us know if solves your problem.

**Comment by mbsantiago** [comment]
Hi there,

@Jeff37 @jenstangchristensen , we've implemented the necessary changes to address the issue. You can now obtain the updated fixes by upgrading your batdetect2 package using pip:

`pip install -U batdetect2`

This will ensure you have the latest versions with the resolved problem. Feel free to give it a try and let us know if everything is working as expected.

**Comment by Jeff37** [comment]
Hi!
Yes Sir, it works!!! Thank you so much once more for your quick reaction :-)
