### ISSUE TITLE
Error processing example audio files on Ubuntu 22.04

### ISSUE THREAD

**Issue by kdarras** [macaodha/batdetect2#3]
After installing Anaconda 3 and running "python run_batdetect.py example_data/audio/ example_data/anns/ 0.3":

![Screenshot from 2023-03-29 14-18-54](https://user-images.githubusercontent.com/7696198/228852762-14f5fccf-440a-4c01-9ccf-fbdd71d2fdb5.png)

Also ran this after manually creating the output folder, same error. No output is created.

**Comment by macaodha** [comment]
Hi there.  Can you share an example audio file so we can debug this.

**Comment by kdarras** [comment]
they are the audio example files that are provided within your batdetect2:
![image](https://user-images.githubusercontent.com/7696198/228535208-144fc713-386b-49e6-8a10-25ecb8313c68.png)

**Comment by macaodha** [comment]
Hi again. In `run_batdetect.py`, can you change the following lines:

```
    for ii, audio_file in enumerate(files):
        print('\n' + str(ii).ljust(6) + os.path.basename(audio_file))
        try:
            results = du.process_file(audio_file, model, params, args)
            if args['save_preds_if_empty'] or (len(results['pred_dict']['annotation']) > 0):
                results_path = audio_file.replace(args['audio_dir'], args['ann_dir'])
                du.save_results_to_file(results, results_path)
        except:
            error_files.append(audio_file)
            print("Error processing file!")
```

to this:
```
    for ii, audio_file in enumerate(files):
        print('\n' + str(ii).ljust(6) + os.path.basename(audio_file))
        results = du.process_file(audio_file, model, params, args)
        if args['save_preds_if_empty'] or (len(results['pred_dict']['annotation']) > 0):
            results_path = audio_file.replace(args['audio_dir'], args['ann_dir'])
            du.save_results_to_file(results, results_path)
```
This should give you a more detailed error that you can share here.

**Comment by macaodha** [comment]
Yes, looks like it. Can I ask what version of librosa you are using, the requirements file calls for `librosa==0.9.2`.

**Comment by kdarras** [comment]
I use librosa 0.10.0
Apparently this was not downgraded during the environment creation. Should I somehow downgrade manually?

**Comment by macaodha** [comment]
Great - glad you got it working. We will look into updating the code so that the latest version on librosa is used. I'll keep the issue open for now to remind myself.

**Comment by kdarras** [comment]
Excellent - looking forward! batdetect2 worked nicely with some sample 10-min Audiomoth recordings, just now.

**Comment by mbsantiago** [comment]
Hi both! This issue has been addressed in a branch we've been working on. Will merge the changes soon 👍🏽.

**Comment by macaodha** [comment]
@kdarras cool, will be interested to see how well it works for you. 

BTW we have an online demo here that you can also try if interested:  
https://huggingface.co/spaces/macaodha/batdetect2
