### ISSUE TITLE
Error processing file!: negative dimensions are not allowed

### ISSUE THREAD

**Issue by Jeff37** [macaodha/batdetect2#31]
Hi there!
Guys, I'm facing an error while processing a data set. I work through anaconda console: `batdetect2 detect "my/input/path" "my/input/path/anns" 0.3 --time_expansion_factor 1 --spec_features` . I'm applying this within my workflow tens of times without error, but recently I processed several data sets (coming from the 2 different Batlogger S2) and the python process stops with:

> "331 /home/jf/ECOFIRST Dropbox/JF Godeau (LIFE)/Ecofirst_Validation_CHIRO_GDL/Session2_20240531-0611/0166_20240531_223911.wav"
[2272] "Error processing file!: negative dimensions are not allowed"

When I remove the file and re-run, it goes further and eventually stops again on the next error. I finally excluded 5 wav files out of 3360 wav and therefore the process goes to the end without errors. I conclude that it is file dependent!
Surprisingly, these problematic files can be processed correctly though the GUI on [huggingface](https://huggingface.co/spaces/macaodha/batdetect2) , the correct ID's are given in the output !?
Is it possible to understand what is wrong with these files, hunt for other problematic files and remove them? Any help deeply appreciated.

**Comment by mbsantiago** [comment]
Hey @Jeff37, could you share the example recording so I can try to tease out the error? You can zip the file and attach it here if it's less than 25MB is size.

**Comment by Jeff37** [comment]
Hi @mbsantiago I attach here the files (+ copy of the lines showing the error from the console). Thanks for checking this out!
[Fichiers_corrompus.zip](https://github.com/user-attachments/files/17386283/Fichiers_corrompus.zip)

**Comment by Jeff37** [comment]
Dear @mbsantiago could you throw an eye on my files?

**Comment by mbsantiago** [comment]
Hi @Jeff37 ! Sorry, haven't had the time yet, but I plan to focus fully on batdetect2 all November. Will have an answer soon.

**Comment by Jeff37** [comment]
Thank you @mbsantiago for fixing the issue! I'll update and give a try ASAP.
